name: "Setup Copilot"
description: "Setup Copilot based on the project's package.json file."
outputs:
  cli-path:
    description: "Path to the Copilot CLI"
    value: ${{ steps.cli-path.outputs.path }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v6
      with:
        cache: "npm"
        cache-dependency-path: "./nodejs/package-lock.json"
        node-version: 22
    - name: Install dependencies
      run: npm --prefix "$(pwd)/nodejs" ci --ignore-scripts
      shell: bash
    - name: Set CLI path
      id: cli-path
      run: echo "path=${COPILOT_CLI_PATH:-$(which copilot-core)}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Verify CLI works
      run: ${{ steps.cli-path.outputs.path }} --version
      shell: bash
